### ISSUE TITLE
First Jigsaw piece is drawn wrong

### ISSUE THREAD

**Issue by erkyrath** [curiousdannii/ifvms.js#45]
I've noticed this before, but I thought it was a glkote error. It's not.

In Jigsaw (R3, serial 951129) if you go `E. W. X PIECE` you should see a piece with two flat sides and two innie sides. ZVM/Lectrote instead draws one flat, two innie, one outie.

Repeating `TURN PIECE` four times shows an inconsistent rotation.

The JSON handed to glkote is already wrong. (See attached file, which I copied from the JS console after some debugging.) Either ZVM is making incorrect output calls, or glkapi.js is handling the calls wrong. I haven't looked further into this.

**Comment by erkyrath** [comment]
[jigsaw-glkote.txt](https://github.com/curiousdannii/ifvms.js/files/837365/jigsaw-glkote.txt)

**Comment by curiousdannii** [comment]
GlkOte's output of NBSP and regular spaces isn't working. The last regular space of each line is lost, so the pieces are only 6 spaces wide rather than 7. If you can add `white-space: pre-wrap` to the GlkOte styles then this problem is fixed. pre-wrap is supported even by IE8 so there shouldn't be any issues with it. With pre-wrap you wouldn't need the NBSPs any longer, but I know you don't like to change what isn't broken, so there's no real need to.

When I've added pre-wrap it seems to work fine to me. Are you certain the JSON is wrong?

**Comment by erkyrath** [comment]
Of the five lines, four start with nine spaces but the middle one starts with ten spaces. That's wrong (as compared with nfrotz's output) -- the left edge of the piece should be flat.

Remapped to ASCII:

    .........#######
    .........#######
    ..........######.
    .........#######
    .........###.###

Not showing the last space on a line -- you're right about that! I'll fix it. But that's an error on the right edge.

(Or is this a RNG difference, where the two interpreters reliably start up selecting different pieces? Hm! Let me fix my error and I'll see how it looks.)

**Comment by curiousdannii** [comment]
>(Or is this a RNG difference, where the two interpreters reliably start up selecting different pieces? Hm! Let me fix my error and I'll see how it looks.)

It's random to some extent, I've seen two different rotations in the one terp after restarting many times. It didn't feel balanced to me, but maybe that's just a perception bias of some kind.

**Comment by erkyrath** [comment]
Yeah, it was all glkote all along. Sorry about that.
